### ISSUE TITLE
No binary for v0.3.x release

### ISSUE THREAD

**Issue by Birkalo** [rslint/rslint#136]
Hi, 

My team is looking into replacing eslint with rslint for our monorepo, and we are planning on downloading the binaries for rslint as part of the process but it looks like the swap to github actions hasn't relased a binary for v0.3.0 and v0.3.1 - can this be fixed, or can the binary be manually uploaded please? 

If so, we'll be able to more easily adopt this into our workflow 

Thanks,
Toby

**Comment by Stupremee** [comment]
I'm sorry for the inconvenience. When I released v0.3.x the CI was broken for the release workflow so it didn't upload them and after 0.3.1 I stopped working on rslint because I didn't have time for it at the time.

However, I can upload the binaries manually for now and when I start working on rslint again I will fix CI for the next releases.

**Comment by Stupremee** [comment]
@Birkalo I published a new release with the fixed CI and there are now binaries available!

Sorry for the long delay.

**Comment by Stupremee** [comment]
I noticed that in the latest release only Linux binary is uploaded. This will be fixed in the next release!
